# Editor used to edit the configuration file.
# Acceptable values: nano, vim, or any terminal or graphical text editor.
PREF_EDITOR=${EDITOR-vim}

# Preferred browser used to extract YouTube cookies.
# Acceptable values: brave-browser-stable, chrome, chromium, edge, firefox, opera, vivaldi
PREF_BROWSER=firefox

# Browser program used to open links externally.
# Acceptable values: Any browser binary
LINK_BROWSER=firefox

# List Length: the number of video results per page.
# Acceptable values: 10 - 60 (smaller values yield faster responses)
LIST_LENGTH=30

# Terminal message duration (sleep command in seconds)
TERMINAL_MESSAGE_DURATION=2

# Messages in color
# Acceptable values: yes, no
COLORED_MESSAGES=yes

# Enable desktop notifications
# Acceptable values: yes, no
NOTIFICATION_ENABLED=yes

# Notification duration (milliseconds)
NOTIFICATION_DURATION=6000

# Image support program for terminal previews.
# Acceptable values: kitty, ueberzugpp, ueberzug, chafa, none
IMAGE_SUPPORT=ueberzugpp

########### Comments ###########

# Show comments and description in terminal during playback.
# Acceptable values: yes, no
COMMENTS_TOGGLE=yes

# Maximum comments loaded per video.
COMMENTS_MAX=100

# Maximum comment replies loaded per comment.
COMMENT_REPLIES_MAX=5

# Comments sort method on YouTube side.
# Acceptable values: new, old, top
COMMENTS_SORT=new

# Show pinned comment as first or last in section.
# Acceptable values: first, last
PINNED_COMMENTS=last

#################################

# Show mpv keybindings
# Acceptable values: yes, no
SHOW_MPV_KEYBINDINGS=no

# Download directory (relative to $HOME or absolute)
DOWNLOAD_DIRECTORY=/Downloads

#################################

# Use Nerd Font icons in UI
# Acceptable values: yes, no
USE_NERD_FONTS=yes
